## Python Programming Tutorial for Beginners
Instructor: Gunnar Pope  
Dartmouth College, ENGS 27 2024X  
Date: 6/25/24 

### Introduction
This tutorial is designed for students with little to no programming experience. We will cover the basics of Python programming, including arrays, lists, dictionaries, loops, file reading, using pandas for .csv files, functions, classes, linear algebra operations, and running test cases.

### Prerequisites
- Basic understanding of computers
- Python installed on your computer (preferably version 3.x)
- A code editor (such as VSCode, PyCharm, Anaconda, or even a simple text editor)

### Table of Contents
1. Arrays and Lists
2. Dictionaries
3. Loops
4. Reading a File
5. Importing a .csv File using Pandas
6. Creating a Function
7. Creating a Class
8. Running a Test Case
9. Linear Algebra Operations
10. Plotting Data

---


### 1. Arrays and Lists
In Python, lists are more commonly used than arrays. Lists are versatile and can hold different data types.

In [67]:
# Creating a list
fruits = ["apple", "banana", "cherry"]
print(fruits)

# Accessing elements
print(fruits[0])  # Output: apple
print(fruits[1])  # Output: banana

# Adding elements
fruits.append("orange")
print(fruits)

# Removing elements
fruits.remove("banana")
print(fruits)

['apple', 'banana', 'cherry']
apple
banana
['apple', 'banana', 'cherry', 'orange']
['apple', 'cherry', 'orange']



### 2. Dictionaries
Dictionaries in Python are used to store data values in key:value pairs.


In [68]:
# Creating a dictionary
student = {"name": "John", "age": 21, "courses": ["Math", "Science"]}

# Accessing values
print(student["name"])  # Output: John
print(student["courses"])  # Output: ['Math', 'Science']

# Adding a key-value pair
student["grade"] = "A"
print(student)

# Removing a key-value pair
del student["age"]
print(student)



John
['Math', 'Science']
{'name': 'John', 'age': 21, 'courses': ['Math', 'Science'], 'grade': 'A'}
{'name': 'John', 'courses': ['Math', 'Science'], 'grade': 'A'}


### 3. Loops
Loops are used for iterating over a sequence (like a list, tuple, dictionary, set, or string).

In [69]:

# For loop with a list
for fruit in fruits:
    print(fruit)

# While loop
count = 0
while count < 5:
    print(count)
    count += 1



apple
cherry
orange
0
1
2
3
4


### 4. Reading a File
Reading files is a common operation in Python. We use the built-in `open` function.


In [70]:
# Reading a file
with open("example.txt", "r") as file:
    content = file.read()
    print(content)



hello engs27!



### 5. Importing a .csv File using Pandas
Pandas is a powerful library for data manipulation and analysis.


In [71]:
# Importing data file using pandas
import pandas as pd

data = {'name': ['John', 'Anna', 'Peter', 'Linda'], 'age': [25, 36, 29, 42]}
df = pd.DataFrame(data)
df.to_csv("example.csv", index=False)  # Save the dataframe to a .csv file

# Reading a .csv file
df2 = pd.read_csv("example.csv")
print(df2.head())  # Display the first few rows of the dataframe



    name  age
0   John   25
1   Anna   36
2  Peter   29
3  Linda   42


### 6. Creating a Function
Functions are reusable pieces of code that perform a specific task.


In [72]:
# Defining a function
def greet(name):
    return f"Hello, {name}!"

# Calling a function
print(greet("Alice"))  # Output: Hello, Alice!



Hello, Alice!


### 7. Creating a Class
Classes are a way to create objects in Python. An object has properties (attributes) and methods (functions).


In [73]:
# Defining a class
class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def display(self):
        return f"Student Name: {self.name}, Age: {self.age}"
         # Braces remove from string

# Creating an object
student1 = Student("Alice", 20)

# Accessing methods
print(student1.display())  # Output: Student Name: Alice, Age: 20



Student Name: Alice, Age: 20



### 8. Running a Test Case
Testing ensures that your code works as expected. Python has a built-in module called `unittest`.

In [74]:
""" Create unit tests for a program, unittest_example.py 
    This is most commonly used within a python file (unitest_example.py) and 
    not within a Jupyter notebook (as the code below is written in a script format).
    Run the tests:
    $ python mycode.py
"""
import unittest

# Function to be tested
def add(a, b):
    return a + b

# Define test cases
class TestAddFunction(unittest.TestCase):
    def test_add_positive_numbers(self):
        self.assertEqual(add(1, 2), 3)
    
    def test_add_negative_numbers(self):
        self.assertEqual(add(-1, -2), -3)
    
    def test_add_zero(self):
        self.assertEqual(add(0, 0), 0)
    
    def test_add_positive_and_negative(self):
        self.assertEqual(add(1, -1), 0)

    def test_fail(self):
        self.assertNotEqual(add(1, 1), 3)

# Run the tests
if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False) # use if running in Jupyter notebook
    # unittest.main() # use if running in a python script


.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK


### 9. Vectors and Linear Algebra Operations in Python
NumPy arrays are similar to Python lists but provide more functionality, especially for mathematical operations.

In [75]:
import numpy as np

# Creating a NumPy array
array = np.array([1, 2, 3, 4, 5])
print(array)

# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## Basic Array Operations
NumPy allows for efficient element-wise operations.

In [76]:
# Element-wise addition
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = array1 + array2
print(result)  # Output: [5 7 9]

# Element-wise multiplication
result = array1 * array2
print(result)  # Output: [ 4 10 18]


[5 7 9]
[ 4 10 18]


## Linear Algebra Operations
Dot Product

The dot product is a common operation in linear algebra.

In [77]:
# Dot product
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
dot_product = np.dot(vector1, vector2)
print(dot_product)  # Output: 32


32


In [78]:
# The outer product
outer_product = np.outer(vector1, vector2)
print(outer_product)  


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### 10. Plotting Data

In [ ]:
# Plotting Data Example
# use matplotlib to plot a sine wave
%matplotlib inline 
#I HAD TO ADD THIS LINE TO GET IT TO WORK SO THAT IT WAS INLINE
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure(figsize=(10, 6))
plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.title('Sine Wave')
plt.grid()
plt.show()


RuntimeError: 'widget' is not a recognised GUI loop or backend name